version: '3'

networks:
  app-tier-python3-v1:
    driver: bridge

services:
  web:
    build: ../../images/python-3.6
    container_name: web-python3-v1
    restart: always
    ports:
     - 8000:8000
    volumes:
     - ./src:/usr/src/app
    command: ["python", "./app.py"]
    networks:
     - app-tier-python3-v1